[package]
name = "aoc2024"
version = "0.1.0"
authors = ["Gian Perrone <foss@gian-perrone.de>"]
edition = "2021"

[dependencies]
anyhow = "1.0.94"
itertools = "0.13.0"
ndarray = "0.16.1"
num = "0.4"
strum = { version = "0.26", features = ["derive"] }
regex = "1.11.1"
